/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PuzzleService } from "../puzzle.service";
import { PuzzleCreateInput } from "./PuzzleCreateInput";
import { Puzzle } from "./Puzzle";
import { PuzzleFindManyArgs } from "./PuzzleFindManyArgs";
import { PuzzleWhereUniqueInput } from "./PuzzleWhereUniqueInput";
import { PuzzleUpdateInput } from "./PuzzleUpdateInput";
import { SubmissionFindManyArgs } from "../../submission/base/SubmissionFindManyArgs";
import { Submission } from "../../submission/base/Submission";
import { SubmissionWhereUniqueInput } from "../../submission/base/SubmissionWhereUniqueInput";

export class PuzzleControllerBase {
  constructor(protected readonly service: PuzzleService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Puzzle })
  async createPuzzle(@common.Body() data: PuzzleCreateInput): Promise<Puzzle> {
    return await this.service.createPuzzle({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        letters: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Puzzle] })
  @ApiNestedQuery(PuzzleFindManyArgs)
  async puzzles(@common.Req() request: Request): Promise<Puzzle[]> {
    const args = plainToClass(PuzzleFindManyArgs, request.query);
    return this.service.puzzles({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        letters: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Puzzle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async puzzle(
    @common.Param() params: PuzzleWhereUniqueInput
  ): Promise<Puzzle | null> {
    const result = await this.service.puzzle({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        letters: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Puzzle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePuzzle(
    @common.Param() params: PuzzleWhereUniqueInput,
    @common.Body() data: PuzzleUpdateInput
  ): Promise<Puzzle | null> {
    try {
      return await this.service.updatePuzzle({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          letters: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Puzzle })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePuzzle(
    @common.Param() params: PuzzleWhereUniqueInput
  ): Promise<Puzzle | null> {
    try {
      return await this.service.deletePuzzle({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          letters: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/submissions")
  @ApiNestedQuery(SubmissionFindManyArgs)
  async findSubmissions(
    @common.Req() request: Request,
    @common.Param() params: PuzzleWhereUniqueInput
  ): Promise<Submission[]> {
    const query = plainToClass(SubmissionFindManyArgs, request.query);
    const results = await this.service.findSubmissions(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        word: true,
        score: true,

        student: {
          select: {
            id: true,
          },
        },

        puzzle: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/submissions")
  async connectSubmissions(
    @common.Param() params: PuzzleWhereUniqueInput,
    @common.Body() body: SubmissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      submissions: {
        connect: body,
      },
    };
    await this.service.updatePuzzle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/submissions")
  async updateSubmissions(
    @common.Param() params: PuzzleWhereUniqueInput,
    @common.Body() body: SubmissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      submissions: {
        set: body,
      },
    };
    await this.service.updatePuzzle({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/submissions")
  async disconnectSubmissions(
    @common.Param() params: PuzzleWhereUniqueInput,
    @common.Body() body: SubmissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      submissions: {
        disconnect: body,
      },
    };
    await this.service.updatePuzzle({
      where: params,
      data,
      select: { id: true },
    });
  }
}
